[package]
name = "xagrs"
version = "0.1.0"
authors = ["Thiago Arrais <thiago.arrais@gmail.com>"]
edition = "2018"
license = "MIT"
description = "xargs clone in Rust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
